name: Deploy Demo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build step
        run: echo "The build has been successfully completed!"

  deploy-to-staging:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Deploy to Staging
        run: echo “Deploy to staging with key ${{ secrets.STAGING_SECRET }}”

  deploy-to-qa:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: qa
    steps:
      - name: Deploy to QA
        run: echo “Deploy to qa with key ${{ secrets.QA_SECRET }}”

  deploy-to-production:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
    steps:
      - name: Deploy to Production
        run: echo “Deploy to production with key ${{ secrets.PROD_SECRET }}”
