name: Deploy PROD

on:
  push:
    tags:
      - 'v*.*.*-prod'

jobs:
  call-ci:
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: call-ci
    runs-on: ubuntu-latest
    if: |
      startsWith(github.ref, 'refs/tags/v') &&
      github.ref_name.endsWith('-prod') &&
      contains(github.event.repository.default_branch, 'main') &&
      github.event.base_ref == 'refs/heads/main' || github.event.ref == 'refs/heads/main' || github.ref == 'refs/heads/main'
    environment:
      name: qa
    steps:
      - uses: actions/checkout@v4
      - name: Check commit branch
        id: check_branch
        run: |
          branch=$(git branch -r --contains ${{ github.sha }} | grep origin/main || true)
          if [ -z "$branch" ]; then
            echo “Tag does not point to main, the deploy will not be executed.”
            exit 1
          fi
      - name: Deploy to QA
        run: echo "DEPLOY PROD ${{ github.ref_name }} with key ${{ secrets.PROD_SECRET }}"
