name: Deploy DEV

on:
  push:
    tags:
      - 'v*.*.*-dev'

jobs:
  call-ci:
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: call-ci
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v4
      - name: Check tag branch
        id: check_main
        run: |
          branch=$(git branch -r --contains ${{ github.sha }} | grep origin/main || true)
          if [ -z "$branch" ]; then
            echo “Tag does not point to main, the deploy will not be executed.”
            exit 1
          fi
      - name: Deploy to Dev
        run: echo "DEPLOY DEV ${{ github.ref_name }} with key ${{ secrets.STAGING_SECRET }}"
